import type { Metadata } from 'next';
import { ReactNode } from 'react';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'x.com',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body style={{ margin: 0 }}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
